spring:
  application:
    name: library-management
  datasource:
    url: jdbc:mysql://localhost:3306/library?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Th@ni2005
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  security:
    oauth2:
      client:
        registration:
          google:
            client-id:  ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email

  mail:
    host: smtp.gmail.com
    port: 587
    username: thaniyarasik@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


aws:
  region: ${AWS_REGION:us-east-1}
  s3:
    bucket-name: ${AWS_S3_BUCKET:book-cover-images-lms}
  sqs:
    bookdue-queue-url: https://sqs.us-east-1.amazonaws.com/975050173010/library-bookdue-notification

jwt:
  secret: 4g9s8K2nL7mQ5xP1vB6rT3yH8jF0wZcA4g9s8K2nL7mQ5xP1
  expiration: 3600000 #60m

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        security: DEBUG
